packages:
  - apps/*
  - packages/*
  - tools/*

allowBuilds:
  vite-plus-monorepo@https://codeload.github.com/voidzero-dev/vite-plus/tar.gz: true

catalogMode: prefer

catalog:
  "@types/node": ^24
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.3.1
  vite-plus: 0.3.1
overrides:
  vite@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
